org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.4)
forge_version=47.1.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1
mod_id=arcademod
mod_name=Arcade Reloaded
mod_license=GPL-3.0-only
mod_version=1.0-1.20.1-sigf1
mod_group_id=superhb.arcademod
mod_authors=Bay4lly (1.20.1 port), SuperHB (1.12.2 original)
mod_description=Adds working arcade machines into Minecraft! SIGF build: all art and sounds replaced with original ones, game names changed.
